# Generated by Django 4.2.11 on 2024-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cat', '0002_menuitem_is_featured_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
