# Generated by Django 4.2.11 on 2024-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cat', '0003_menuitem_discount_menuitem_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
