# Generated by Django 4.2.11 on 2024-05-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cat', '0009_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loyalty_card_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='loyalty_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe_cat.loyaltycard'),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
