# Generated by Django 4.2.11 on 2024-05-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cat', '0010_remove_profile_loyalty_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_points_used',
            field=models.BooleanField(default=False),
        ),
    ]
