# Generated by Django 4.2.11 on 2024-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cat', '0012_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_points',
            field=models.IntegerField(default=100),
        ),
    ]
