# Generated by Django 4.2.11 on 2024-05-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_cat', '0013_order_loyalty_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='loyalty_points',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
